/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "controlunit.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(railway_Device, railway_Device, 2)


PB_BIND(railway_ControlUnit, railway_ControlUnit, 4)





