name=GoogleProtobuf
version=1.0
author=google
maintainer=google
sentence=google Protobuf
paragraph=google Protobuf
category=Communication
url=https://github.com/protocolbuffers/protobuf
architectures=*
dot_a_linkage=true