// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlunit.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_controlunit_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_controlunit_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_controlunit_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_controlunit_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_controlunit_2eproto;
namespace railway {
class ControlUnit;
struct ControlUnitDefaultTypeInternal;
extern ControlUnitDefaultTypeInternal _ControlUnit_default_instance_;
class Device;
struct DeviceDefaultTypeInternal;
extern DeviceDefaultTypeInternal _Device_default_instance_;
}  // namespace railway
PROTOBUF_NAMESPACE_OPEN
template<> ::railway::ControlUnit* Arena::CreateMaybeMessage<::railway::ControlUnit>(Arena*);
template<> ::railway::Device* Arena::CreateMaybeMessage<::railway::Device>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace railway {

enum DeviceType : int {
  Train = 0,
  Turnout = 1
};
bool DeviceType_IsValid(int value);
constexpr DeviceType DeviceType_MIN = Train;
constexpr DeviceType DeviceType_MAX = Turnout;
constexpr int DeviceType_ARRAYSIZE = DeviceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeviceType_descriptor();
template<typename T>
inline const std::string& DeviceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DeviceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DeviceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DeviceType_descriptor(), enum_t_value);
}
inline bool DeviceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DeviceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DeviceType>(
    DeviceType_descriptor(), name, value);
}
enum Function : int {
  Default = 0,
  Music = 1
};
bool Function_IsValid(int value);
constexpr Function Function_MIN = Default;
constexpr Function Function_MAX = Music;
constexpr int Function_ARRAYSIZE = Function_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Function_descriptor();
template<typename T>
inline const std::string& Function_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Function>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Function_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Function_descriptor(), enum_t_value);
}
inline bool Function_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Function* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Function>(
    Function_descriptor(), name, value);
}
// ===================================================================

class Device final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:railway.Device) */ {
 public:
  inline Device() : Device(nullptr) {}
  ~Device() override;
  explicit constexpr Device(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Device(const Device& from);
  Device(Device&& from) noexcept
    : Device() {
    *this = ::std::move(from);
  }

  inline Device& operator=(const Device& from) {
    CopyFrom(from);
    return *this;
  }
  inline Device& operator=(Device&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Device& default_instance() {
    return *internal_default_instance();
  }
  static inline const Device* internal_default_instance() {
    return reinterpret_cast<const Device*>(
               &_Device_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Device& a, Device& b) {
    a.Swap(&b);
  }
  inline void Swap(Device* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Device* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Device* New() const final {
    return new Device();
  }

  Device* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Device>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Device& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Device& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Device* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "railway.Device";
  }
  protected:
  explicit Device(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFunctionsFieldNumber = 3,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // repeated .railway.Function Functions = 3;
  int functions_size() const;
  private:
  int _internal_functions_size() const;
  public:
  void clear_functions();
  private:
  ::railway::Function _internal_functions(int index) const;
  void _internal_add_functions(::railway::Function value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_functions();
  public:
  ::railway::Function functions(int index) const;
  void set_functions(int index, ::railway::Function value);
  void add_functions(::railway::Function value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& functions() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_functions();

  // required string id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // required .railway.DeviceType type = 2;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::railway::DeviceType type() const;
  void set_type(::railway::DeviceType value);
  private:
  ::railway::DeviceType _internal_type() const;
  void _internal_set_type(::railway::DeviceType value);
  public:

  // @@protoc_insertion_point(class_scope:railway.Device)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> functions_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  int type_;
  friend struct ::TableStruct_controlunit_2eproto;
};
// -------------------------------------------------------------------

class ControlUnit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:railway.ControlUnit) */ {
 public:
  inline ControlUnit() : ControlUnit(nullptr) {}
  ~ControlUnit() override;
  explicit constexpr ControlUnit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ControlUnit(const ControlUnit& from);
  ControlUnit(ControlUnit&& from) noexcept
    : ControlUnit() {
    *this = ::std::move(from);
  }

  inline ControlUnit& operator=(const ControlUnit& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlUnit& operator=(ControlUnit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlUnit& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlUnit* internal_default_instance() {
    return reinterpret_cast<const ControlUnit*>(
               &_ControlUnit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ControlUnit& a, ControlUnit& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlUnit* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlUnit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ControlUnit* New() const final {
    return new ControlUnit();
  }

  ControlUnit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ControlUnit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ControlUnit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ControlUnit& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlUnit* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "railway.ControlUnit";
  }
  protected:
  explicit ControlUnit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .railway.Device device = 2;
  int device_size() const;
  private:
  int _internal_device_size() const;
  public:
  void clear_device();
  ::railway::Device* mutable_device(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::railway::Device >*
      mutable_device();
  private:
  const ::railway::Device& _internal_device(int index) const;
  ::railway::Device* _internal_add_device();
  public:
  const ::railway::Device& device(int index) const;
  ::railway::Device* add_device();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::railway::Device >&
      device() const;

  // required string id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // @@protoc_insertion_point(class_scope:railway.ControlUnit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::railway::Device > device_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  friend struct ::TableStruct_controlunit_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Device

// required string id = 1;
inline bool Device::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Device::has_id() const {
  return _internal_has_id();
}
inline void Device::clear_id() {
  id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Device::id() const {
  // @@protoc_insertion_point(field_get:railway.Device.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Device::set_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:railway.Device.id)
}
inline std::string* Device::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:railway.Device.id)
  return _s;
}
inline const std::string& Device::_internal_id() const {
  return id_.Get();
}
inline void Device::_internal_set_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Device::_internal_mutable_id() {
  _has_bits_[0] |= 0x00000001u;
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Device::release_id() {
  // @@protoc_insertion_point(field_release:railway.Device.id)
  if (!_internal_has_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Device::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:railway.Device.id)
}

// required .railway.DeviceType type = 2;
inline bool Device::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Device::has_type() const {
  return _internal_has_type();
}
inline void Device::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::railway::DeviceType Device::_internal_type() const {
  return static_cast< ::railway::DeviceType >(type_);
}
inline ::railway::DeviceType Device::type() const {
  // @@protoc_insertion_point(field_get:railway.Device.type)
  return _internal_type();
}
inline void Device::_internal_set_type(::railway::DeviceType value) {
  assert(::railway::DeviceType_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  type_ = value;
}
inline void Device::set_type(::railway::DeviceType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:railway.Device.type)
}

// repeated .railway.Function Functions = 3;
inline int Device::_internal_functions_size() const {
  return functions_.size();
}
inline int Device::functions_size() const {
  return _internal_functions_size();
}
inline void Device::clear_functions() {
  functions_.Clear();
}
inline ::railway::Function Device::_internal_functions(int index) const {
  return static_cast< ::railway::Function >(functions_.Get(index));
}
inline ::railway::Function Device::functions(int index) const {
  // @@protoc_insertion_point(field_get:railway.Device.Functions)
  return _internal_functions(index);
}
inline void Device::set_functions(int index, ::railway::Function value) {
  assert(::railway::Function_IsValid(value));
  functions_.Set(index, value);
  // @@protoc_insertion_point(field_set:railway.Device.Functions)
}
inline void Device::_internal_add_functions(::railway::Function value) {
  assert(::railway::Function_IsValid(value));
  functions_.Add(value);
}
inline void Device::add_functions(::railway::Function value) {
  _internal_add_functions(value);
  // @@protoc_insertion_point(field_add:railway.Device.Functions)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
Device::functions() const {
  // @@protoc_insertion_point(field_list:railway.Device.Functions)
  return functions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Device::_internal_mutable_functions() {
  return &functions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Device::mutable_functions() {
  // @@protoc_insertion_point(field_mutable_list:railway.Device.Functions)
  return _internal_mutable_functions();
}

// -------------------------------------------------------------------

// ControlUnit

// required string id = 1;
inline bool ControlUnit::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ControlUnit::has_id() const {
  return _internal_has_id();
}
inline void ControlUnit::clear_id() {
  id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ControlUnit::id() const {
  // @@protoc_insertion_point(field_get:railway.ControlUnit.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlUnit::set_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:railway.ControlUnit.id)
}
inline std::string* ControlUnit::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:railway.ControlUnit.id)
  return _s;
}
inline const std::string& ControlUnit::_internal_id() const {
  return id_.Get();
}
inline void ControlUnit::_internal_set_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ControlUnit::_internal_mutable_id() {
  _has_bits_[0] |= 0x00000001u;
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ControlUnit::release_id() {
  // @@protoc_insertion_point(field_release:railway.ControlUnit.id)
  if (!_internal_has_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ControlUnit::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:railway.ControlUnit.id)
}

// repeated .railway.Device device = 2;
inline int ControlUnit::_internal_device_size() const {
  return device_.size();
}
inline int ControlUnit::device_size() const {
  return _internal_device_size();
}
inline void ControlUnit::clear_device() {
  device_.Clear();
}
inline ::railway::Device* ControlUnit::mutable_device(int index) {
  // @@protoc_insertion_point(field_mutable:railway.ControlUnit.device)
  return device_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::railway::Device >*
ControlUnit::mutable_device() {
  // @@protoc_insertion_point(field_mutable_list:railway.ControlUnit.device)
  return &device_;
}
inline const ::railway::Device& ControlUnit::_internal_device(int index) const {
  return device_.Get(index);
}
inline const ::railway::Device& ControlUnit::device(int index) const {
  // @@protoc_insertion_point(field_get:railway.ControlUnit.device)
  return _internal_device(index);
}
inline ::railway::Device* ControlUnit::_internal_add_device() {
  return device_.Add();
}
inline ::railway::Device* ControlUnit::add_device() {
  ::railway::Device* _add = _internal_add_device();
  // @@protoc_insertion_point(field_add:railway.ControlUnit.device)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::railway::Device >&
ControlUnit::device() const {
  // @@protoc_insertion_point(field_list:railway.ControlUnit.device)
  return device_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace railway

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::railway::DeviceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::railway::DeviceType>() {
  return ::railway::DeviceType_descriptor();
}
template <> struct is_proto_enum< ::railway::Function> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::railway::Function>() {
  return ::railway::Function_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_controlunit_2eproto
