M48
; DRILL file {KiCad 9.0.7} date 2026-04-29T21:56:38+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-29T21:56:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
%
G90
G05
T1
X4.7697Y-1.2648
T2
X4.1535Y-2.2244
X4.2126Y-2.2244
M30
